"""Safe, responsive baseline templates for a new notification-platform installation."""

DEFAULT_TEMPLATES = {
    "REPORT_READY": {
        "subject": "Your report {{ report_name }} is ready",
        "body": "Hello,\n\nYour report '{{ report_name }}' is ready to view.",
        "sms_body": "Your report {{ report_name }} is ready.",
        "html_body": """<!doctype html><html><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#162033"><div style="max-width:600px;margin:32px auto;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 8px 28px rgba(15,35,70,.12)"><div style="padding:30px 36px;background:linear-gradient(135deg,#2563eb,#4f46e5);color:#fff"><div style="font-size:13px;letter-spacing:1.4px;font-weight:bold">NOTIFICATION CENTER</div><h1 style="margin:12px 0 0;font-size:27px">Your report is ready</h1></div><div style="padding:32px 36px"><p style="font-size:16px;line-height:1.6;margin-top:0">Your requested report has been generated and is ready to review.</p><div style="padding:18px 20px;border-radius:10px;background:#eef4ff;border-left:4px solid #2563eb"><div style="font-size:12px;color:#52627a;text-transform:uppercase;letter-spacing:1px">Report</div><div style="font-size:18px;font-weight:bold;margin-top:5px">{{ report_name }}</div></div><p style="font-size:14px;line-height:1.6;color:#52627a;margin:28px 0 0">This is an automated notification. Please contact your administrator if you did not expect it.</p></div><div style="padding:18px 36px;background:#f8fafc;color:#718096;font-size:12px">Notification Platform</div></div></body></html>""",
    },
    "PAYMENT_FAILED": {
        "subject": "Action needed: payment {{ payment_id }} was not completed",
        "body": "Hello,\n\nPayment {{ payment_id }} for {{ amount }} could not be processed. Reason: {{ reason }}",
        "sms_body": "Payment {{ payment_id }} for {{ amount }} failed. {{ reason }}",
        "html_body": """<!doctype html><html><body style="margin:0;background:#fdf4f4;font-family:Arial,sans-serif;color:#2b2020"><div style="max-width:600px;margin:32px auto;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 8px 28px rgba(100,25,25,.12)"><div style="padding:30px 36px;background:linear-gradient(135deg,#b91c1c,#dc2626);color:#fff"><div style="font-size:13px;letter-spacing:1.4px;font-weight:bold">PAYMENT ALERT</div><h1 style="margin:12px 0 0;font-size:27px">Payment needs attention</h1></div><div style="padding:32px 36px"><p style="font-size:16px;line-height:1.6;margin-top:0">We could not complete your payment. No successful payment has been recorded.</p><table role="presentation" style="width:100%;border-collapse:separate;border-spacing:0;background:#fff5f5;border:1px solid #fecaca;border-radius:10px"><tr><td style="padding:15px 18px;color:#7f1d1d;font-size:13px">Payment ID</td><td style="padding:15px 18px;text-align:right;font-weight:bold">{{ payment_id }}</td></tr><tr><td style="padding:15px 18px;border-top:1px solid #fecaca;color:#7f1d1d;font-size:13px">Amount</td><td style="padding:15px 18px;border-top:1px solid #fecaca;text-align:right;font-weight:bold">{{ amount }}</td></tr><tr><td style="padding:15px 18px;border-top:1px solid #fecaca;color:#7f1d1d;font-size:13px">Reason</td><td style="padding:15px 18px;border-top:1px solid #fecaca;text-align:right">{{ reason }}</td></tr></table><p style="font-size:14px;line-height:1.6;color:#7c5b5b;margin:28px 0 0">Please try again or contact support if the issue continues.</p></div><div style="padding:18px 36px;background:#fff8f8;color:#8b6b6b;font-size:12px">Notification Platform</div></div></body></html>""",
    },
    "SYSTEM_ALERT": {
        "subject": "System alert: {{ service_name }} requires attention",
        "body": "System alert for {{ service_name }}: {{ message }}",
        "sms_body": "Alert: {{ service_name }} — {{ message }}",
        "html_body": """<!doctype html><html><body style="margin:0;background:#fffbeb;font-family:Arial,sans-serif;color:#2f2a1d"><div style="max-width:600px;margin:32px auto;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 8px 28px rgba(100,75,10,.12)"><div style="padding:30px 36px;background:linear-gradient(135deg,#b45309,#f59e0b);color:#fff"><div style="font-size:13px;letter-spacing:1.4px;font-weight:bold">SYSTEM ALERT</div><h1 style="margin:12px 0 0;font-size:27px">Action may be required</h1></div><div style="padding:32px 36px"><div style="padding:18px 20px;border-radius:10px;background:#fffbeb;border-left:4px solid #f59e0b"><div style="font-size:12px;color:#786636;text-transform:uppercase;letter-spacing:1px">Affected service</div><div style="font-size:18px;font-weight:bold;margin-top:5px">{{ service_name }}</div><p style="font-size:15px;line-height:1.6;margin:14px 0 0">{{ message }}</p></div><p style="font-size:14px;line-height:1.6;color:#756647;margin:28px 0 0">Review the service and its logs to determine whether intervention is necessary.</p></div><div style="padding:18px 36px;background:#fffdf5;color:#8c7a57;font-size:12px">Notification Platform</div></div></body></html>""",
    },
}
